name: Auto approve PRs by Copilot

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto-approve:
    if: github.actor == 'toguri'
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

